const { v4: uuidv4 } = require('uuid')

const sentEmailData = [
  {
    to: 'sarah.johnson@gmail.com',
    from: 'melinda smith',
    subject: 'Welcome to Our Travel Community',
    body: "<p>Dear Sarah Johnson,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Travel Adventures does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>Sarah Johnson</p>",
    read: true,
    openedAt: new Date('2024-10-20T09:15:22.000Z'),
    trackingId: uuidv4(),
    createdAt: new Date('2024-10-20T09:10:15.408Z'),
    updatedAt: new Date('2024-10-20T09:15:22.939Z'),
  },
  {
    to: 'mike.brown@yahoo.com',
    from: 'melinda smith',
    subject: 'Exciting Travel Opportunities Await',
    body: "<p>Dear Mike Brown,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Wanderlust Blog does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>Mike Brown</p>",
    read: false,
    openedAt: null,
    trackingId: uuidv4(),
    createdAt: new Date('2024-10-21T14:30:45.408Z'),
    updatedAt: new Date('2024-10-21T14:30:45.408Z'),
  },
  {
    to: 'emily.davis@hotmail.com',
    from: 'melinda smith',
    subject: 'Your Travel Story Matters',
    body: "<p>Dear Emily Davis,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Global Explorers does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>Emily Davis</p>",
    read: true,
    openedAt: new Date('2024-10-22T16:42:18.000Z'),
    trackingId: uuidv4(),
    createdAt: new Date('2024-10-22T16:35:12.408Z'),
    updatedAt: new Date('2024-10-22T16:42:18.721Z'),
  },
  {
    to: 'david.wilson@outlook.com',
    from: 'melinda smith',
    subject: 'Join Our Travel Writing Team',
    body: "<p>Dear David Wilson,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Journey Chronicles does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>David Wilson</p>",
    read: true,
    openedAt: new Date('2024-10-23T11:28:33.000Z'),
    trackingId: uuidv4(),
    createdAt: new Date('2024-10-23T11:20:08.408Z'),
    updatedAt: new Date('2024-10-23T11:28:33.156Z'),
  },
  {
    to: 'lisa.martinez@gmail.com',
    from: 'melinda smith',
    subject: 'Travel Content Creator Opportunity',
    body: "<p>Dear Lisa Martinez,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Adventure Seekers does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>Lisa Martinez</p>",
    read: false,
    openedAt: null,
    trackingId: uuidv4(),
    createdAt: new Date('2024-10-24T08:45:27.408Z'),
    updatedAt: new Date('2024-10-24T08:45:27.408Z'),
  },
  {
    to: 'robert.garcia@icloud.com',
    from: 'melinda smith',
    subject: 'Share Your Adventures With Us',
    body: "<p>Dear Robert Garcia,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Nomad Stories does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>Robert Garcia</p>",
    read: true,
    openedAt: new Date('2024-10-25T13:17:44.000Z'),
    trackingId: uuidv4(),
    createdAt: new Date('2024-10-25T13:12:33.408Z'),
    updatedAt: new Date('2024-10-25T13:17:44.892Z'),
  },
  {
    to: 'anna.thompson@protonmail.com',
    from: 'melinda smith',
    subject: 'Collaborate With Travel Enthusiasts',
    body: "<p>Dear Anna Thompson,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Backpack Diaries does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>Anna Thompson</p>",
    read: false,
    openedAt: null,
    trackingId: uuidv4(),
    createdAt: new Date('2024-10-26T10:22:15.408Z'),
    updatedAt: new Date('2024-10-26T10:22:15.408Z'),
  },
  {
    to: 'chris.anderson@yahoo.com',
    from: 'melinda smith',
    subject: 'Travel Writing Partnership',
    body: "<p>Dear Chris Anderson,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Route Discoveries does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>Chris Anderson</p>",
    read: true,
    openedAt: new Date('2024-10-27T15:33:12.000Z'),
    trackingId: uuidv4(),
    createdAt: new Date('2024-10-27T15:28:44.408Z'),
    updatedAt: new Date('2024-10-27T15:33:12.677Z'),
  },
  {
    to: 'jessica.white@gmail.com',
    from: 'melinda smith',
    subject: 'Destination Guide Contributors Wanted',
    body: "<p>Dear Jessica White,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Explorer's Hub does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>Jessica White</p>",
    read: true,
    openedAt: new Date('2024-10-28T12:45:28.000Z'),
    trackingId: uuidv4(),
    createdAt: new Date('2024-10-28T12:40:19.408Z'),
    updatedAt: new Date('2024-10-28T12:45:28.334Z'),
  },
  {
    to: 'kevin.lee@hotmail.com',
    from: 'melinda smith',
    subject: 'Travel Community Invitation',
    body: "<p>Dear Kevin Lee,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Wanderer's Journal does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>Kevin Lee</p>",
    read: false,
    openedAt: null,
    trackingId: uuidv4(),
    createdAt: new Date('2024-10-29T09:15:37.408Z'),
    updatedAt: new Date('2024-10-29T09:15:37.408Z'),
  },
  {
    to: 'michelle.clark@outlook.com',
    from: 'melinda smith',
    subject: 'Featured Travel Writer Position',
    body: "<p>Dear Michelle Clark,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Travel Tales does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>Michelle Clark</p>",
    read: true,
    openedAt: new Date('2024-10-30T14:52:16.000Z'),
    trackingId: uuidv4(),
    createdAt: new Date('2024-10-30T14:47:22.408Z'),
    updatedAt: new Date('2024-10-30T14:52:16.789Z'),
  },
  {
    to: 'daniel.harris@gmail.com',
    from: 'melinda smith',
    subject: 'Weekly Travel Newsletter Team',
    body: "<p>Dear Daniel Harris,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Journey Insights does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>Daniel Harris</p>",
    read: false,
    openedAt: null,
    trackingId: uuidv4(),
    createdAt: new Date('2024-10-31T11:33:48.408Z'),
    updatedAt: new Date('2024-10-31T11:33:48.408Z'),
  },
  {
    to: 'rachel.rodriguez@icloud.com',
    from: 'melinda smith',
    subject: 'Travel Photography Collaboration',
    body: "<p>Dear Rachel Rodriguez,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Visual Voyages does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>Rachel Rodriguez</p>",
    read: true,
    openedAt: new Date('2024-11-01T16:24:35.000Z'),
    trackingId: uuidv4(),
    createdAt: new Date('2024-11-01T16:18:12.408Z'),
    updatedAt: new Date('2024-11-01T16:24:35.445Z'),
  },
  {
    to: 'steven.walker@protonmail.com',
    from: 'melinda smith',
    subject: 'Guest Blogger Opportunity',
    body: "<p>Dear Steven Walker,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Passport Pages does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>Steven Walker</p>",
    read: true,
    openedAt: new Date('2024-11-02T13:41:27.000Z'),
    trackingId: uuidv4(),
    createdAt: new Date('2024-11-02T13:35:55.408Z'),
    updatedAt: new Date('2024-11-02T13:41:27.612Z'),
  },
  {
    to: 'nicole.hall@yahoo.com',
    from: 'melinda smith',
    subject: 'Monthly Travel Feature Story',
    body: "<p>Dear Nicole Hall,</p><br><p>I hope this message finds you well. I am reaching out because of my passion for travel and my admiration for the inspiring work that Adventure Chronicles does in connecting travelers worldwide.</p><br><p>As a dedicated travel enthusiast, I would love the opportunity to contribute to your platform. Whether it's sharing unique travel experiences, creating destination guides, or offering tips for fellow travelers, I believe I can add value to your community.</p><br><p>Thank you for considering my request. I look forward to the possibility of working together.</p><br><p>Warm regards,<br>Nicole Hall</p>",
    read: false,
    openedAt: null,
    trackingId: uuidv4(),
    createdAt: new Date('2024-11-03T10:27:43.408Z'),
    updatedAt: new Date('2024-11-03T10:27:43.408Z'),
  },
]

module.exports = { sentEmailData }
